[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:worker]
command=uvicorn main:app --host 0.0.0.0 --port 9000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:comfyui]
command=python3 main.py --listen 0.0.0.0 --port 8188 --extra-model-paths-config /opt/comfyui/extra_model_paths.yaml
directory=/opt/comfyui
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
